apiVersion: apps/v1

kind: Deployment

metadata:

  name: todo-deployment
  namespace: django
  labels:

    app: todo-app

spec:

  replicas: 3

  selector:

    matchLabels:

      app: todo-app

  template:

    metadata:
      namespace: django
      labels:

        app: todo-app

    spec:

      containers:

      - name: todo-app

        image: comprofessional/django-todo:latest

          #        ports:

          #        - containerPort: 8000
        env:
        - name: PORT
          value: "8001"  # Specify the port here
