apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-8000
        image: comprofessional/django-todo:latest
        env:
        - name: PORT
          value: "8000"
        ports:
        - containerPort: 8000

      - name: todo-app-8001
        image: comprofessional/django-todo:latest
        env:
        - name: PORT
          value: "8001"
        ports:
        - containerPort: 8001

      - name: todo-app-8002
        image: comprofessional/django-todo:latest
        env:
        - name: PORT
          value: "8002"
        ports:
        - containerPort: 8002

