apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: django
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    
    - name: http-port
      port: 80
      targetPort: 8000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007

      # Second external port mapping
    
    - name: http-port-2
      port: 81
      targetPort: 8001
      nodePort: 30008

    # Third external port mapping
    
    - name: http-port-3
      port: 82
      targetPort: 8002
      nodePort: 30009
